version: '3.8'
networks:
  novalogistic-net:
    driver: bridge

services:
  # EUREKA SERVER 
  eureka-server:
    build: ./eureka_server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - novalogistic-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. MICROSERVICIO USUARIOS
  ms-usuarios:
    build: ./ms_usuarios
    container_name: ms-usuarios
    ports:
      - "8081:8081"
    networks:
      - novalogistic-net
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # 3. MICROSERVICIO OPERACIONES (Ejemplo adicional)
  ms-operaciones:
    build: ./ms-operaciones
    container_name: ms-operaciones
    ports:
      - "8084:8084" 
    networks:
      - novalogistic-net
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # 4. API GATEWAY 
  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - novalogistic-net
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/