server:
  port: 8081

spring:
  application:
    name: ms-usuarios
  
  # Conexión a tu Base de Datos Oracle con la Wallet
  datasource:
    url: jdbc:oracle:thin:@bdnovalogistic_high?TNS_ADMIN=C:/Users/darie/Downloads/Wallet_BDNOVALOGISTIC
    username: ADMIN
    password: Novalogistic4590
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Conexión al Directorio Central (Eureka)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
