server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # Obliga a Eureka a leer todo en minúsculas
      mvc:
        routes:
          # 1. Rutas hacia MS-Usuarios (MINÚSCULAS)
          - id: ms-usuarios
            uri: lb://ms_usuarios
            predicates:
              - Path=/api/v1/clientes/**

          # 2. Rutas hacia MS-Operaciones
          - id: ms-operaciones
            uri: lb://ms_operaciones
            predicates:
              - Path=/api/v1/envios/**

          # 3. Rutas hacia MS-Infraestructura
          - id: ms-infraestructura
            uri: lb://ms_infraestructura
            predicates:
              - Path=/api/v1/sucursal/**

          # 4. Rutas hacia MS-Comercial
          - id: ms-comercial
            uri: lb://ms_comercial
            predicates:
              - Path=/api/v1/precio/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/