CREATE TABLE envio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_guia VARCHAR2(20) UNIQUE NOT NULL,
    id_cliente BIGINT NOT NULL,
    id_paquete BIGINT NOT NULL,
    direccion_destino VARCHAR2(50) NOT NULL,
    ciudad_destino VARCHAR2(20) NOT NULL,
    precio NUMBER(10,2) NOT NULL CHECK (precio BETWEEN 500 AND 10000),
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_envio BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_envio_paquete FOREIGN KEY (id_paquete) REFERENCES paquete(id)
);
